// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvTGkj_FtL2il1aU7AWZ4pM2Svc-qLnyc',
    appId: '1:905845816339:web:924ad4cf1d0cc9bfd813e6',
    messagingSenderId: '905845816339',
    projectId: 'fir-demoapp-afe2a',
    authDomain: 'fir-demoapp-afe2a.firebaseapp.com',
    storageBucket: 'fir-demoapp-afe2a.appspot.com',
    measurementId: 'G-CNC6X28C5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl8TQOxg_mekyd69B_xGeeok2NKPIgn_k',
    appId: '1:905845816339:android:e0b9fdd2f079121cd813e6',
    messagingSenderId: '905845816339',
    projectId: 'fir-demoapp-afe2a',
    storageBucket: 'fir-demoapp-afe2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_SCUAkQg7obcwjFdb3rIP3PwDodU21M',
    appId: '1:905845816339:ios:40333ac27d3a654ed813e6',
    messagingSenderId: '905845816339',
    projectId: 'fir-demoapp-afe2a',
    storageBucket: 'fir-demoapp-afe2a.appspot.com',
    iosClientId: '905845816339-rrrhk1di3j22eaga3ee9jmbdi384mbi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn_SCUAkQg7obcwjFdb3rIP3PwDodU21M',
    appId: '1:905845816339:ios:40333ac27d3a654ed813e6',
    messagingSenderId: '905845816339',
    projectId: 'fir-demoapp-afe2a',
    storageBucket: 'fir-demoapp-afe2a.appspot.com',
    iosClientId: '905845816339-rrrhk1di3j22eaga3ee9jmbdi384mbi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );
}
